/**
 * API Route Stubs for SoundScout Explore
 *
 * Auto-generated by Claudery Blueprint Generator
 *
 * Copy these to your app/api/ directory and customize as needed.
 * Each function represents a separate route handler.
 */

import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

// ============================================
// AUTH ROUTES
// ============================================

/**
 * POST /api/auth/signin
 */
export async function POST_SIGNIN(request: NextRequest) {
  const supabase = await createClient();
  const { email, password } = await request.json();

  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });

  if (error) {
    return NextResponse.json({ error: { code: "AUTH_ERROR", message: error.message } }, { status: 401 });
  }

  return NextResponse.json({ data: { user: data.user } });
}

/**
 * POST /api/auth/signup
 */
export async function POST_SIGNUP(request: NextRequest) {
  const supabase = await createClient();
  const { email, password } = await request.json();

  const { data, error } = await supabase.auth.signUp({
    email,
    password,
  });

  if (error) {
    return NextResponse.json({ error: { code: "AUTH_ERROR", message: error.message } }, { status: 400 });
  }

  return NextResponse.json({ data: { user: data.user } }, { status: 201 });
}

/**
 * POST /api/auth/signout
 */
export async function POST_SIGNOUT() {
  const supabase = await createClient();
  await supabase.auth.signOut();
  return NextResponse.json({ success: true });
}

/**
 * GET /api/auth/me
 */
export async function GET_ME() {
  const supabase = await createClient();
  const { data: { user }, error } = await supabase.auth.getUser();

  if (error || !user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  return NextResponse.json({ data: { user } });
}


// ============================================
// EVENT ROUTES
// ============================================

/**
 * GET /api/events
 * List all events for current user
 */
export async function GET_EVENTS(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const limit = parseInt(searchParams.get("limit") || "20");
  const offset = parseInt(searchParams.get("offset") || "0");

  const { data, error, count } = await supabase
    .from("events")
    .select("*", { count: "exact" })
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({
    data,
    pagination: { total: count || 0, limit, offset, hasMore: (count || 0) > offset + limit },
  });
}

/**
 * POST /api/events
 * Create new event
 */
export async function POST_EVENTS(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();
  // TODO: Add zod validation

  const { data, error } = await supabase
    .from("events")
    .insert({ ...body, user_id: user.id })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data }, { status: 201 });
}

/**
 * GET /api/events/[id]
 * Get single event by ID
 */
export async function GET_EVENT_BY_ID(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { data, error } = await supabase
    .from("events")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", user.id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: { code: "NOT_FOUND" } }, { status: 404 });
  }

  return NextResponse.json({ data });
}

/**
 * PUT /api/events/[id]
 * Update event
 */
export async function PUT_EVENT(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();

  const { data, error } = await supabase
    .from("events")
    .update(body)
    .eq("id", params.id)
    .eq("user_id", user.id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data });
}

/**
 * DELETE /api/events/[id]
 * Delete event
 */
export async function DELETE_EVENT(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { error } = await supabase
    .from("events")
    .delete()
    .eq("id", params.id)
    .eq("user_id", user.id);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}

// ============================================
// ARTIST ROUTES
// ============================================

/**
 * GET /api/artists
 * List all artists for current user
 */
export async function GET_ARTISTS(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const limit = parseInt(searchParams.get("limit") || "20");
  const offset = parseInt(searchParams.get("offset") || "0");

  const { data, error, count } = await supabase
    .from("artists")
    .select("*", { count: "exact" })
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({
    data,
    pagination: { total: count || 0, limit, offset, hasMore: (count || 0) > offset + limit },
  });
}

/**
 * POST /api/artists
 * Create new artist
 */
export async function POST_ARTISTS(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();
  // TODO: Add zod validation

  const { data, error } = await supabase
    .from("artists")
    .insert({ ...body, user_id: user.id })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data }, { status: 201 });
}

/**
 * GET /api/artists/[id]
 * Get single artist by ID
 */
export async function GET_ARTIST_BY_ID(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { data, error } = await supabase
    .from("artists")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", user.id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: { code: "NOT_FOUND" } }, { status: 404 });
  }

  return NextResponse.json({ data });
}

/**
 * PUT /api/artists/[id]
 * Update artist
 */
export async function PUT_ARTIST(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();

  const { data, error } = await supabase
    .from("artists")
    .update(body)
    .eq("id", params.id)
    .eq("user_id", user.id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data });
}

/**
 * DELETE /api/artists/[id]
 * Delete artist
 */
export async function DELETE_ARTIST(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { error } = await supabase
    .from("artists")
    .delete()
    .eq("id", params.id)
    .eq("user_id", user.id);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}

// ============================================
// VENUE ROUTES
// ============================================

/**
 * GET /api/venues
 * List all venues for current user
 */
export async function GET_VENUES(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { searchParams } = new URL(request.url);
  const limit = parseInt(searchParams.get("limit") || "20");
  const offset = parseInt(searchParams.get("offset") || "0");

  const { data, error, count } = await supabase
    .from("venues")
    .select("*", { count: "exact" })
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({
    data,
    pagination: { total: count || 0, limit, offset, hasMore: (count || 0) > offset + limit },
  });
}

/**
 * POST /api/venues
 * Create new venue
 */
export async function POST_VENUES(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();
  // TODO: Add zod validation

  const { data, error } = await supabase
    .from("venues")
    .insert({ ...body, user_id: user.id })
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data }, { status: 201 });
}

/**
 * GET /api/venues/[id]
 * Get single venue by ID
 */
export async function GET_VENUE_BY_ID(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { data, error } = await supabase
    .from("venues")
    .select("*")
    .eq("id", params.id)
    .eq("user_id", user.id)
    .single();

  if (error || !data) {
    return NextResponse.json({ error: { code: "NOT_FOUND" } }, { status: 404 });
  }

  return NextResponse.json({ data });
}

/**
 * PUT /api/venues/[id]
 * Update venue
 */
export async function PUT_VENUE(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const body = await request.json();

  const { data, error } = await supabase
    .from("venues")
    .update(body)
    .eq("id", params.id)
    .eq("user_id", user.id)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ data });
}

/**
 * DELETE /api/venues/[id]
 * Delete venue
 */
export async function DELETE_VENUE(request: NextRequest, { params }: { params: { id: string } }) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const { error } = await supabase
    .from("venues")
    .delete()
    .eq("id", params.id)
    .eq("user_id", user.id);

  if (error) {
    return NextResponse.json({ error: { code: "DB_ERROR", message: error.message } }, { status: 500 });
  }

  return NextResponse.json({ success: true });
}

// ============================================
// HELPER: Create actual route files
// ============================================

/*
To use these stubs, create route files like:

app/api/items/route.ts:
-----------------------
import { GET_ITEMS, POST_ITEMS } from "@/lib/api-stubs";
export { GET_ITEMS as GET, POST_ITEMS as POST };

app/api/items/[id]/route.ts:
---------------------------
import { GET_ITEM_BY_ID, PUT_ITEM, DELETE_ITEM } from "@/lib/api-stubs";
export { GET_ITEM_BY_ID as GET, PUT_ITEM as PUT, DELETE_ITEM as DELETE };
*/
